#server port number
server:
  port: 9090

#view Resolver
spring:  mvc:    view:      prefix: /WEB-INF/views/
      suffix: .jsp
#--------------------for embeded database-----------------------------------
  #datasource:
    #username: sa
    #password: 
    #url: jdbc:h2:mem:testdb
    #driver-class-name: org.h2.Driver
#-------------------for oracle database--------------------------------------    
  jpa:
    hibernate:
      ddl-auto: update  #while using H2 db we should remove the dilect properties
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect    


  datasource: 
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: scott
    password: tiger 