server:
  port: 9090

spring:  mvc:    view:      prefix: /views/
      suffix: .jsp

    
  datasource:
         url: jdbc:mysql://localhost:3306/gg
         username: root
         password: root
         #url: jdbc:oracle:thin:@localhost:1521:xe 
         #username: scott
         #password: tiger
         #driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:    show-sql: true
    hibernate:      ddl-auto: update
    #properties:
           #hibernate: org.hibernate.dialect.MySQL55Dialect
           #hibernate: org.hibernate.dialect.Oracle10gDilect

