server:
  port: 9090

spring:  mvc:    view:      prefix: /views/
      suffix: .jsp
#-------------------------to insert into the Embeded H2 data base-----------------------      
  datasource:
    username: sa    password:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver  
